PL/Controllers/RolesController.cs
using BLL.ViewModel;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public RolesController(UserManager<ApplicationUser> _userManager,RoleManager<IdentityRole> _roleManager) 
        {
            userManager = _userManager;
            roleManager = _roleManager;
        }
        public async Task<IActionResult> Index()
        {

            var roles = await roleManager.Roles.ToListAsync();
            return View(roles);
        }
        public IActionResult Create()
        { 
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole identityRole)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.CreateAsync(identityRole);
                if (role.Succeeded)
                   return RedirectToAction("Index");
                
                foreach (var error in role.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(identityRole);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var Role = await roleManager.FindByIdAsync(id);

            if (Role is null)
            {
                return NotFound();
            }

            return View(Role);
        }
        public async Task<IActionResult> Update(string id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var Role = await roleManager.FindByIdAsync(id);

            if (Role is null)
            {
                return NotFound();
            }

            return View(Role);
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, IdentityRole identityRole)
        {
            if (id != identityRole.Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                var row = await roleManager.FindByIdAsync(id);
                if (row is null)
                {
                    return NotFound();
                }
                row.Name = identityRole.Name;
                //row.NormalizedName = identityRole.NormalizedName;
                ///row.NormalizedName = identityRole.NormalizedName.ToUpper();

                var res = await roleManager.UpdateAsync(row);
                if (res.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in res.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(identityRole);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var role = await roleManager.FindByIdAsync(id);

            if (role is null)
            {
                return NotFound();
            }


            var deleted = await roleManager.DeleteAsync(role);
            if (deleted.Succeeded)
                return RedirectToAction("Index");


            foreach (var error in deleted.Errors)
                ModelState.AddModelError(string.Empty, error.Description);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddOrRmoveRoleFromUser(string RoleId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);
            if (role is null)
                return NotFound();
            var users = new List<UsersInRoles>();
            ViewBag.RoleId = RoleId;

            foreach(var user in userManager.Users)
            {
                var userInRole = new UsersInRoles()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                    userInRole.isSelected = true;
                else
                    userInRole.isSelected = false;
                
                users.Add(userInRole);

            }

            return View(users);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddOrRmoveRoleFromUser(string RoleId, List<UsersInRoles> usersInRoles)
        {
            var role = await roleManager.FindByIdAsync(RoleId);
            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var item in usersInRoles)
                {
                    var user = await userManager.FindByIdAsync(item.UserId);
                    if (user is not null)
                    {
                        if (item.isSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                            await userManager.AddToRoleAsync(user, role.Name);
                        else
                            await userManager.RemoveFromRoleAsync(user, role.Name);
                    }
                }
                return RedirectToAction("Update", new {id = RoleId});
            }
            return View(usersInRoles);
  
        }
    }
}
    

PL/Controllers/UserController.cs
using AutoMapper;
using BLL.ViewModel;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PL.Helper;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public UserController(UserManager<ApplicationUser> _userManager) 
        {
            userManager = _userManager;
        }
        public IActionResult Index(string SearchValue= "")
        {
            //if (string.IsNullOrEmpty(SearchValue))
            //{
           var res = userManager.Users.ToList();
           return View(res);
            //}
            //else
            //{
            //    var res = await userManager.FindByNameAsync(SearchValue);
            //    return View(new List<ApplicationUser>{ res});
            //}
        }

        public async Task<IActionResult> Details(string id)
        {
            if(id is null)
            {
                return NotFound();
            }
            var user = await userManager.FindByIdAsync(id);

            if (user is null)
            {
                return NotFound();
            }

            return View(user);
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var user = await userManager.FindByIdAsync(id);

            if (user is null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id,ApplicationUser Newdata)
        {
            if (id is null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                var row = await userManager.FindByIdAsync(id);
                if (row is null)
                {
                    return NotFound();
                }
                row.PhoneNumber = Newdata.PhoneNumber;
                row.UserName = Newdata.UserName;
                row.NormalizedUserName = Newdata.UserName.ToUpper();
                
                var res= await userManager.UpdateAsync(row);
                if(res.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in res.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(Newdata);
        }
        public async Task<IActionResult> delete(string id)
        {
            if (id is null)
                return BadRequest();

            var user = await userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound();

            var deleted = await userManager.DeleteAsync(user);
            if (deleted.Succeeded)
                return RedirectToAction("Index");


            foreach (var error in deleted.Errors)
                ModelState.AddModelError(string.Empty, error.Description);

            return RedirectToAction("Index");
        }
    }


}

PL/Views/Roles/AddOrRmoveRoleFromUser.cshtml
@model List<UsersInRoles> 
@{
    ViewData["Title"] = "AddOrRmoveRoleFromUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AddOrRmoveRoleFromUser</h1>

<div class="row">
    <div class="col-6">
        <form asp-action="AddOrRmoveRoleFromUser" asp-controller="Roles" asp-route-RoleId="@ViewBag.RoleId">
            @for (int i = 0; i < Model.Count; i++)
            {
             <div class="form-group">
                    <label asp-for="@Model[i].isSelected" class="col-form-label">@Model[i].UserName</label>
                    <input asp-for="@Model[i].isSelected" class="form-control" /><br />
            </div>
            
            <input asp-for="@Model[i].UserId" type="hidden" class="form-control" />
            <input asp-for="@Model[i].UserName" type="hidden"  class="form-control" />

            <br />
            

            }
            <input type="submit" value="update" /><br />
            <a asp-action="Index" class="btn btn-light">back</a>
            <a asp-action="Update" class="btn btn-light" asp-controller="Roles"
            asp-route-RoleId="@ViewBag.RoleId">cancel</a>


        </form>
    </div>
</div>

PL/Views/Roles/Create.cshtml
@model IdentityRole
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<div class="row">
    <div class="col-6">
        <form asp-action="Create" asp-controller="Roles">
            @*<input hidden asp-for="@Model.Id" />*@
            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label"></label>
                <input asp-for="@Model.Name" placeholder="UserName" class="form-control" /><br />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>


            <input type="submit" value="Create" /><br />
            <a asp-action="Index" asp-controller="Roles" class="btn btn-light">back</a>
        </form>
    </div>
</div>

PL/Views/Roles/Details.cshtml
@model IdentityRole
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<br />
<br />

<div class="row">
    <div class="col-12">
        <div class="form-group">
            <label asp-for="@Model.Id" class="col-from-label"></label>
            <input asp-for="@Model.Id" class="form-control" readonly />
        </div>
        <div class="form-group">
            <label asp-for="@Model.Name" class="col-from-label"></label>
            <input asp-for="@Model.Name" class="form-control" readonly />
        </div>
        <br />
        <a class="btn btn-success" asp-action="update" asp-route-id="@Model.Id">edit</a>
        <a class="btn btn-info" asp-action="Index">back</a>

    </div>
</div>

PL/Views/Roles/Index.cshtml
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>All Roles</h1>

@*<a asp-action="create" asp-controller="User" class="btn btn-primary">create User</a>*@

@*@if(ViewBag.MessageBag != null){
    <div class=" align-content-center">
    <h3 class="m-auto font-weight-bold alert-danger">@ViewBag.MessageBag</h3>
    </div>
}
@if(ViewData["MessageData"] != null){
<div class="align-content-center">
    <h3 class="m-auto alert-danger">@ViewData["MessageData"]</h3>
</div>
}*@

@*@if (TempData["Message"] != null)
{
    <div class="align-content-center">
        <h3 class="m-auto alert-danger">@TempData["Message"]</h3>
    </div>
}*@
<a asp-action="create" asp-controller="Roles" class="btn btn-primary">create a role</a>

<br />
<br />
<form class="my-3" asp-action="Index" asp-controller="User">
    <div class="row">
        <div class="col-sm-8">
            <input placeholder="Search by Name" name="searchValue" class="form-control" />
        </div>
        <div class="col-sm-4">
            <input type="submit" value="search" class="btn btn-success btn-block" />
        </div>
    </div>
</form>

@if ((Model?.Count() > 0))
{
    <table class="table table-dark">
        <thead>
            <tr>
                @*<th scope="col">#</th>*@
                <th scope="col">@Html.DisplayNameFor(a=>a.Id)</th>
                <th scope="col">@Html.DisplayNameFor(a=>a.Name)</th>
                <th scope="col">details</th>
                <th scope="col">edit</th>
                <th scope="col">delete</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <partial name="ButtonsViewPartial" model="@item.Id.ToString()"></partial>
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <div class="alert alert-warning mt-5">
        <h3>no users found</h3>
    </div>

}

PL/Views/Roles/Update.cshtml
@model IdentityRole
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>



<div class="row">
    <div class="col-6">
        <form asp-action="update" asp-asp-controller="Roles">
            <input hidden asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label"></label>
                <input asp-for="@Model.Name" placeholder="UserName" class="form-control" /><br />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="my-3">
                <a class="btn btn-info" asp-action="AddOrRmoveRoleFromUser"
                   asp-controller="Roles" asp-route-RoleId="@Model.Id">add role to user Or Remove Role from user</a>
            </div>
            <input type="submit" value="update" /><br />
            <a asp-action="Index" class="btn btn-light">back</a>
        </form>
    </div>
</div>