PL/Controllers/DepartmentController.cs
using AutoMapper;
using BLL.Interfaces;
using BLL.ViewModel;
using DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork context;
        private readonly IMapper mapper;

        public DepartmentController(IUnitOfWork _context,IMapper _Mapper) 
        {
            context = _context;
            mapper = _Mapper;
        }
        public async Task<IActionResult> Index()
        {
            var departments = await context.DepartmentRepo.GetAll();
            var Row = mapper.Map<IEnumerable<Department>,IEnumerable<DepartmentViewModel>>(departments);

            return View(Row);
        }
        [HttpGet]
        public IActionResult create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> create(DepartmentViewModel department)
        {
            if(ModelState.IsValid)
            {
                var DeptCreated = mapper.Map<DepartmentViewModel,Department>(department);
                await context.DepartmentRepo.AddEntity(DeptCreated);
                return RedirectToAction("Index");
            }
            return View(department);
        }

        public async Task<IActionResult> details(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var department = await context.DepartmentRepo.GetById(id);
            var detail = mapper.Map<Department,DepartmentViewModel>(department);

            if(detail is null)
            {
                return NotFound();
            }

            return View(detail);
        }

        public async Task<IActionResult> delete(int? id)
        {
            if(id is null)
            {
                return NotFound();
            }
            var row = await context.DepartmentRepo.GetById(id);

            if (row is null)
            {
                return NotFound();
            }
            await context.DepartmentRepo.DeleteEntity(row);

            return RedirectToAction("Index");

        }

        public async Task<IActionResult> update(int? id)
        {
            if(id is null)
            {
                return NotFound();
            }
            var row =await context.DepartmentRepo.GetById(id);
            var rowToUpdate= mapper.Map<DepartmentViewModel>(row);

            if(row is null)
            {
                return NotFound();
            }

            //await context.UpdateDepartment(row);
            return View(rowToUpdate);
        }
        [HttpPost]
        public async Task<IActionResult> update(int? id, DepartmentViewModel department)
        {

            if (id != department.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var deptToEdit = mapper.Map<DepartmentViewModel, Department>(department);

                    await context.DepartmentRepo.UpdateEntity(deptToEdit);
                    return RedirectToAction("Index");
                }
                catch(Exception e)
                {
                    return View(department);
                }
            }
            return View(department);
        }

    }
}

PL/Views/Department/Details.cshtml
@model DepartmentViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Department Details</h1>

<br />
<br />

<div class="row">
    <div class="col-12">
         <div class="form-group">
             <label asp-for="@Model.code"  class="col-from-label"></label>
             <input asp-for="@Model.code" class="form-control" readonly />
         </div>
        <div class="form-group">
            <label asp-for="@Model.Name" class="col-from-label"></label>
            <input asp-for="@Model.Name" class="form-control" readonly />
        </div>
        <div class="form-group">
            <label asp-for="@Model.DateOfCreation" class="col-from-label"></label>
            <input asp-for="@Model.DateOfCreation" class="form-control" readonly />
        </div>
        <br />
        <a class="btn btn-success" asp-action="update" asp-route-id="@Model.Id">edit</a>
        <a class="btn btn-info" asp-action="Index">back</a>

    </div>
</div>

PL/Views/Department/Index.cshtml
@model IEnumerable<DepartmentViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>All Departments</h1>

<br />

<a asp-action="create" asp-controller="Department" class="btn btn-primary">create department</a>
@if((Model?.Count()> 0))
{
    <table class="table table-dark">
        <thead>
            <tr>
                @*<th scope="col">#</th>*@
                <th scope="col">@Html.DisplayNameFor(a=>a.code)</th>
                <th scope="col">@Html.DisplayNameFor(a=>a.Name)</th>
                <th scope="col">details</th>
                <th scope="col">edit</th>
                <th scope="col">delete</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                
                <tr>
                    @*<td>@</td>*@
                    <td>@item.code</td>
                    <td>@item.Name</td>

                    <partial name="ButtonsViewPartial" model="@item.Id.ToString()"></partial>
                </tr>
            }
        </tbody>
    </table>
    
}
else{
    <div class="alert alert-warning mt-5">
        <h3>no departments found</h3>
    </div>
    
}

PL/Views/Department/create.cshtml
@model DepartmentViewModel
@{
    ViewData["Title"] = "create";
}

<h1>create</h1>

<div class="row">
    <div class="col-6" >
        <form asp-action="create" asp-asp-controller="Department" >
            <div class="form-group">
           <label asp-for="@Model.Name" class="col-form-label"></label>
                <input asp-for="@Model.Name" placeholder="name" class="form-control" /><br />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="@Model.code" class="col-form-label"></label>
            <input asp-for="@Model.code" placeholder="code" class="form-control" /><br />
            <span asp-validation-for="@Model.code" class="text-danger"></span>

            </div>
@*            <select asp-for="DeptNo" asp-items="ViewBag.dept">
                <option>select department</option>
            </select>*@

            <input type="submit" value="add" /><br />
            <a asp-action="Index" class="btn btn-light">back</a>
        </form>
    </div>
</div>


@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

PL/Views/Department/update.cshtml
@model DepartmentViewModel
@{
    ViewData["Title"] = "update";
}

<h1>update</h1>


<div class="row">
    <div class="col-6">
        <form asp-action="update" asp-asp-controller="Department">
            <input hidden asp-for="@Model.Id" />
            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label"></label>
                <input asp-for="@Model.Name" placeholder="name" class="form-control" /><br />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.code" class="col-form-label"></label>
                <input asp-for="@Model.code" placeholder="code" class="form-control" /><br />
                <span asp-validation-for="@Model.code" class="text-danger"></span>

            </div>
            @*            <select asp-for="DeptNo" asp-items="ViewBag.dept">
            <option>select department</option>
            </select>*@

            <input type="submit" value="update" /><br />
            <a asp-action="Index" class="btn btn-light">back</a>
        </form>
    </div>
</div>


@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}